# web server
nginx:
  image: nginx:latest
  ports:
    - "80:80"
   # - "443:443"
  volumes:
    # app
    - /alidata/workspace/:/www/
    # nginx configs
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    # certificates
    #- ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
    #- ./nginx/ca/server.key/:/etc/nginx/server.key:ro
  #links:
  #  - fpm:__DOCKER_PHP_FPM__
  net: "host"
  # restart policy
  restart : always

# php-fpm
fpm:
  build: ./php-fpm
  ports:
    - "9000"
  volumes:
    - /alidata/workspace/:/www/
    # Your php.ini
    - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
  # environment:
    # Set your APP env variables here:
    # - APP_KEY=
    # - DB_HOST=
    # - DB_DATABASE=
    # - DB_USERNAME=
    # - DB_PASSWORD=
  #links:
  #  - mysql:mysql
  net: "host"
  # restart policy
  restart : always

# database
mysql:
  image: mysql:latest
  ports:
    # Allow client to access 3306
    - "3306:3306"
  volumes:
    # NOTE: your data will be stored in ./mysql
    - ./mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=111111
  #net: "host"
  # restart policy
  restart : always

#redis
redis:
  image: redis:latest
  ports: 
    - "6379:6379"
  volumes:
    - "./redis/data/:/data/"
    - "./redis/conf/:/etc/redis/" 
  command: "redis-server /etc/redis/redis.conf"
  restart: always  
      

